<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Bep6.Unity.Il2Cpp.IMGUI</AssemblyName>
    <Product>My first plugin</Product>
    <Version>{version}</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>Bep6.Unity.Il2Cpp.IMGUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.AutoPlugin" Version="1.*" />
    <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" PrivateAssets="all" ExcludeAssets="runtime" />

    <!-- Analyzers -->
    <PackageReference Include="Harmonize" Version="1.*" />
  </ItemGroup>

  <!-- Replace CoolGame with the environment variable that points to the game folder -->
  <Target Name="Copy" AfterTargets="Build" Condition="'$({game})' != ''">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$({game})/BepInEx/plugins/" UseSymboliclinksIfPossible="true" />
  </Target>
</Project>
